### ISSUE TITLE
investigate and resolve error with pip state

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/fpco-salt-formula#120]
See the upstream issue (saltstack/salt#46163) for more info. Debug and figure out why this is happening. First spotted when running saltstack `2018.3.0`, I need to retest with `2017.7.3`. I also need to make sure an apt upgrade doesn't change anything, or that I have the latest Xenial (as the vagrant image may be out of date). This blocks effective testing and continued development on the formula.

**Comment by ketzacoatl** [comment]
The latest vagrant box, running saltstack `2018.3.0` fails with the same error.

For example:

```
...
    default: ----------
    default:           ID: pip-refresh_modules
    default:     Function: module.wait
    default:         Name: saltutil.refresh_modules
    default:       Result: True
    default:      Comment: Module function saltutil.refresh_modules executed
    default:      Started: 23:16:48.548239
    default:     Duration: 74.733 ms
    default:      Changes:   
    default:               ----------
    default:               ret:
    default:                   True
    default: 
    default: Summary for local
    default: ------------
    default: Succeeded: 6 (changed=5)
    default: Failed:    0
    default: ------------
    default: Total states run:     6
    default: Total run time:  36.034 s
    default: [WARNING ] The function "module.run" is using its deprecated version and will expire in version "Sodium".
    default: [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
    default: [ERROR   ] Command '[u'systemd-run', u'--scope', u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options::=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u'base-pkg']' failed with return code: 100
    default: [ERROR   ] stdout: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: [ERROR   ] stderr: Running scope as unit run-rcb8a3f2094d140c6a4a59efce11bb4df.scope.
    default: E: Unable to locate package base-pkg
    default: [ERROR   ] retcode: 100
    default: [ERROR   ] Problem encountered installing package(s). Additional info follows:
    default: 
    default: errors:
    default:     - Running scope as unit run-rcb8a3f2094d140c6a4a59efce11bb4df.scope.
    default:       E: Unable to locate package base-pkg
    default: [ERROR   ] An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.

...
```

This is Ubuntu `16.04.4`:

```
root@ubuntu-xenial:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ketzacoatl** [comment]
running `apt-get update` and `apt-get upgrade -y` ahead of time does not help, same error.

**Comment by ketzacoatl** [comment]
same thing with the older version of saltstack. now I'm confused.

```
    default:           ID: docker-dependencies
    default:     Function: pip.installed
    default:         Name: docker-py
    default:       Result: False
    default:      Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not inst
alled properly.
    default:      Started: 23:46:12.005619
    default:     Duration: 9.119 ms
    default:      Changes:  
```

**Comment by ketzacoatl** [comment]
```
# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from salt.states import pip_state
>>> dir()
['__builtins__', '__doc__', '__name__', '__package__', 'pip_state', 'salt']
>>> dir(pip_state)
['CommandExecutionError', 'CommandNotFoundError', 'HAS_PIP', 'InstallationError', '_SaltStackVersion', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__virtual__', '__virtualname__', '_check_if_installed', '_check_pkg_version_format', '_find_key', '_fulfills_version_spec', '_pep440_version_cmp', 'absolute_import', 'installed', 'logger', 'logging', 'pkg_resources', 're', 'removed', 'salt', 'six', 'sys', 'uptodate']
>>>
>>> pip_state.installed(name="reclass==1.4.1")                                                                                                                            
{'comment': "An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.", 'changes': {}, 'name': 'reclass==1.4.1', 'result': False}
```

This is interesting.. where is `pip.main()`?

```
>>> import pip
>>> dir(pip)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__']
>>> pip.main(['install', 'reclass==1.4.1'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'main'
```

Pip is in the list of importable paths...
```
>>> import sys
>>> print '\n'.join(sys.path)

/usr/local/lib/python2.7/dist-packages/pip-10.0.1-py2.7.egg
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
```

```
>>> import pip
>>> pip.__file__
'/usr/local/lib/python2.7/dist-packages/pip-10.0.1-py2.7.egg/pip/__init__.pyc'
```

So pip is there, and it's usable.

After a while I figure out that `pip.main()` isn't accessible. Looking a little closer, I see evidence of an internal module shuffle associated with the latest 10.x release. Eventually I found a comment - http://jelly.codes/articles/python-pip-module/#comment-3858610819 - mentioning this:

> Note that using parse_requirements() like this is broken as of pip v10.0.0. (The req module has been moved to _internal.) The authors of pip have stated that they don't actually make any guarantees with regard to pip's internal API's, which means that any code that imports from pip in this way can break at any time. See https://pip.pypa.io/en/stab....

With some testing of versions, I was able to confirm Saltstack `2018.3.0` works fine with pip `9.0.3`, but everything breaks with pip `10.x`.

See some examples of the working/failing in my comment in the upstream issue: https://github.com/saltstack/salt/issues/46163#issuecomment-385240688
